export const MODIFICAR_USUARIO = 'MODIFICAR_USUARIO';
export const MODIFICAR_SENHA = 'MODIFICAR_SENHA';
export const LISTAR_USUARIOS = 'LISTAR_USUARIOS';
export const LISTAR_USUARIOS_SUCESSO = 'LISTAR_USUARIOS_SUCESSO';
export const LISTAR_USUARIOS_ERRO = 'LISTAR_USUARIOS_ERRO';
export const LISTAR_LANCAMENTOS_ANO = 'LISTAR_LANCAMENTOS_ANO';
export const LISTAR_LANCAMENTOS_ANO_SUCESSO = 'LISTAR_LANCAMENTOS_ANO_SUCESSO';
export const LISTAR_LANCAMENTOS_ANO_ERRO = 'LISTAR_LANCAMENTOS_ANO_ERRO';
